version: '3'

volumes:
  postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: compose_example_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: /start
    networks:
      - compose_example

  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    networks:
      - compose_example

  redis:
    image: redis:3.2
    networks:
      - compose_example

  celeryworker:
    <<: *django
    image: compose_example_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: compose_example_celerybeat
    command: /start-celerybeat
    ports: []

networks:
    compose_example:
        driver: bridge
